version: '2'
networks:
  infrastructure_http_traffic:
    external: true
  infrastructure_sql_traffic:
    external: true
  infrastructure_nosql_traffic:
    external: true
  infrastructure_amqp_traffic:
    external: true
  infrastructure_redis_traffic:
    external: true
  infrastructure_rsyslog_traffic:
    external: true
  infrastructure_ssh_traffic:
    external: true

services:
  web1:
    restart: always
    build:
      dockerfile: ./docker/services/http/Dockerfile
      context: .
    image: ddd/http
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:55514"
        tag: "{{.DaemonName}}/web1"
    expose:
      - "80"
    networks:
      infrastructure_http_traffic:
        aliases:
          - web1
      infrastructure_sql_traffic:
        aliases:
          - web1
      infrastructure_nosql_traffic:
        aliases:
          - web1
      infrastructure_amqp_traffic:
        aliases:
          - web1
      infrastructure_redis_traffic:
        aliases:
          - web1
      infrastructure_rsyslog_traffic:
        aliases:
          - web1
      infrastructure_ssh_traffic:
        aliases:
          - web1
    cpu_shares: 1000
    mem_limit: 100m

  web2:
      restart: always
      build:
        dockerfile: ./docker/services/http/Dockerfile
        context: .
      image: ddd/http
      logging:
        driver: syslog
        options:
          syslog-address: "tcp://127.0.0.1:55514"
          tag: "{{.DaemonName}}/web2"
      expose:
        - "80"
      networks:
        infrastructure_http_traffic:
          aliases:
            - web2
        infrastructure_sql_traffic:
          aliases:
            - web2
        infrastructure_nosql_traffic:
          aliases:
            - web2
        infrastructure_amqp_traffic:
          aliases:
            - web2
        infrastructure_redis_traffic:
          aliases:
            - web2
        infrastructure_rsyslog_traffic:
          aliases:
            - web2
        infrastructure_ssh_traffic:
          aliases:
            - web2
      cpu_shares: 1000
      mem_limit: 500m

  eventconsumer:
      restart: always
      build: docker/services/eventconsumer
      image: ddd/consumer

      logging:
        driver: syslog
        options:
          syslog-address: "tcp://127.0.0.1:55514"
          tag: "{{.DaemonName}}/eventconsumer"
      volumes:
        - .:/ddd
      networks:
        infrastructure_nosql_traffic:
          aliases:
            - eventconsumer
        infrastructure_amqp_traffic:
          aliases:
            - eventconsumer
        infrastructure_rsyslog_traffic:
          aliases:
            - eventconsumer
      cpu_shares: 1000
      mem_limit: 120m

    mailerconsumer:
        restart: always
        build: docker/services/mailerconsumer
        image: ddd/mailerconsumer

        logging:
          driver: syslog
          options:
            syslog-address: "tcp://127.0.0.1:55514"
            tag: "{{.DaemonName}}/mailerconsumer"
        volumes:
          - .:/ddd
        networks:
          infrastructure_nosql_traffic:
            aliases:
              - mailerconsumer
          infrastructure_amqp_traffic:
            aliases:
              - mailerconsumer
          infrastructure_rsyslog_traffic:
            aliases:
              - mailerconsumer
        cpu_shares: 1000
        mem_limit: 120m

