version: '2'
networks:
  infrastructure_http_traffic:
    external: true
  infrastructure_sql_traffic:
    external: true
  infrastructure_nosql_traffic:
    external: true
  infrastructure_amqp_traffic:
    external: true
  infrastructure_redis_traffic:
    external: true

services:
  http:
    restart: always
    build: docker/httpdev
    image: ddd/httpdev
    volumes:
      - .:/var/www/html
    expose:
      - 80
    environment:
      - ENABLE_SYMFONY_DEBUG=a8f5f167f44f4964e6c998dee827110c
    networks:
      infrastructure_http_traffic:
        aliases:
          - http
      infrastructure_sql_traffic:
        aliases:
          - http
      infrastructure_nosql_traffic:
        aliases:
          - http
      infrastructure_amqp_traffic:
        aliases:
          - http
      infrastructure_redis_traffic:
        aliases:
          - http
    cpu_shares: 1000
    mem_limit: 100m

