imports:
    - { resource: config.yml }
monolog:
  handlers:
    main:
      type:         fingers_crossed
      action_level: error
      handler:      syslog
      formatter: monolog.formatter.app
    syslog:
      type:         syslogudp
      host:         '%syslog.host%'
      level:        error
#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

