
parameters:

services:

  monolog.processor.app:
    class: DDD\Infrastructure\Web\Symfony\AppBundle\Log\AppLogProcessor
    tags:
      - { name: monolog.processor }
  monolog.formatter.app:
    class: Monolog\Formatter\LineFormatter
    arguments:
      format: "%%datetime%% | %%extra.app%% | %%channel%%.%%level_name%%: %%message%% %%context%%\n"

  doctrine.configurer:
      class: DDD\Infrastructure\Persistence\Doctrine\Configuration\DoctrineConfigurerAdapter
  mongo.configurer:
      class: DDD\Infrastructure\Persistence\Mongo\Configuration\MongoConfigurerAdapter
  rabbitmq.configurer:
      class: DDD\Infrastructure\Message\Amqp\Configuration\AmqpConnectionFactory
  rabbitmq.event.producer:
      class: DDD\Infrastructure\Event\EventProducer
      arguments: ["@rabbitmq.configurer"]
  event.store:
      class: DDD\Infrastructure\Event\EventStore
      arguments: ["@rabbitmq.event.producer"]



