
parameters:

services:

  monolog.processor.app:
    class: DDD\Infrastructure\Web\Symfony\AppBundle\Log\AppLogProcessor
    tags:
      - { name: monolog.processor }
  monolog.formatter.app:
    class: Monolog\Formatter\LineFormatter
    arguments:
      format: "%%datetime%% | %%extra.app%% | %%channel%%.%%level_name%%: %%message%% %%context%%\n"

  doctrine.orm.configurer:
      class: DDD\Infrastructure\Persistence\Doctrine\Orm\Configuration\DoctrineOrmConfigurerAdapter
  doctrine.odm.configurer:
      class: DDD\Infrastructure\Persistence\Doctrine\Odm\Configuration\DoctrineOdmConfigurerAdapter
  mongo.configurer:
      class: DDD\Infrastructure\Persistence\Mongo\Configuration\MongoConfigurerAdapter
  rabbitmq.configurer:
      class: DDD\Infrastructure\Message\Amqp\Configuration\AmqpConnectionFactory


  rabbitmq.event.producer:
      class: DDD\Infrastructure\Message\Amqp\Activity\ActivityProducer
      arguments: ["@rabbitmq.configurer"]

  event.repository:
      class: DDD\Infrastructure\Persistence\Doctrine\Odm\EventStoreRepository
      arguments: ["@doctrine.odm.configurer"]

  rabbitmq.mail.producer:
      class: DDD\Infrastructure\Message\Amqp\Mailer\MailerProducer
      arguments: ["@rabbitmq.configurer"]



