# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

  doctrine.configurer:
      class: DDD\Infrastructure\Persistence\Doctrine\Configuration\DoctrineConfigurerAdapter
  mongo.configurer:
      class: DDD\Infrastructure\Persistence\Mongo\Configuration\MongoConfigurerAdapter
  rabbitmq.configurer:
      class: DDD\Infrastructure\Message\Amqp\Configuration\AmqpConnectionFactory
  rabbitmq.event.producer:
      class: DDD\Infrastructure\Event\EventProducer
      arguments: ["@rabbitmq.configurer"]
  event.store:
      class: DDD\Infrastructure\Event\EventStore
      arguments: ["@rabbitmq.event.producer"]



